name = "KristianHolmeRegistry"
uuid = "c0664469-9f7d-4e61-bca4-afc37dc3cd37"
repo = "git@github.com:KristianHolme/KristianHolmeRegistry"

[packages]
6fae0b71-e89e-4561-9656-794937ecd499 = { name = "RDE_Env", path = "R/RDE_Env" }
